apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/votre-projet/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "votre-adresse-cloudsql"
